name: Publish Presenter Env

on:
  - workflow_dispatch

jobs:
  pipeline:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Checkout action repository
        uses: actions/checkout@v3
        with:
          repository: heronlabs/build-package-action
          ref: 1.1.0
          token: ${{ secrets.AUTHOR_PERSONAL_ACCESS}}
          path: ./build-package-action

      - name: Run action
        uses: './build-package-action/application/github'
        with:
          AUTHOR_PERSONAL_ACCESS: ${{ secrets.AUTHOR_PERSONAL_ACCESS }}

      - name: Checkout action repository
        uses: actions/checkout@v3
        with:
          repository: heronlabs/publish-github-package-action
          ref: 1.0.0
          token: ${{ secrets.AUTHOR_PERSONAL_ACCESS}}
          path: ./publish-github-package-action

      - name: Run action
        uses: './publish-github-package-action/application/github'
        with:
          AUTHOR_PERSONAL_ACCESS: ${{ secrets.AUTHOR_PERSONAL_ACCESS }}
