name: Publish

on:
  - workflow_dispatch

jobs:
  pipeline:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: '[BUILD] | Install Dependencies'
        run: yarn install --frozen-lockfile
        shell: bash

      - name: '[BUILD] | Compile'
        run: yarn compile
        shell: bash

      - name: '[ACTION] | Clone publish github package action'
        uses: actions/checkout@v4
        with:
          repository: heronlabs/publish-github-package-action
          ref: 5.0.0
          token: ${{ secrets.PAT }}
          path: ./publish-github-package-action

      - name: '[ACTION] | Run publish github package action'
        uses: './publish-github-package-action/application/github'
        with:
          PAT: ${{ secrets.PAT }}
